name: javilla
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  get: ^4.7.2
  mysql1: ^0.20.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  shimmer: ^3.0.0
  loading_animation_widget: ^1.3.0
  connectivity_plus: ^7.0.0
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#1c6b50"
  min_sdk_android: 21

# run: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#1c6b50"
  color_dark: "#1c6b50"
  background_image: "assets/images/splash.png"
  android_12:
    color: "#1c6b50"
    color_dark: "#1c6b50"
    icon_background_color: "#1c6b50"
    icon_background_color_dark: "#1c6b50"
    image: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - .env

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-Black.ttf
          weight: 900
